#!/bin/sh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

if ! command -v git &> /dev/null
then
	echo -e "${RED}You should install Git on your machine!${NC}"
	exit 255
fi

if ! command -v go &> /dev/null
then
	echo "${RED}You should install Go>=1.17 on your machine!${NC}"
	exit 255
fi

git clone https://github.com/QuantaPM/quanta-cli $HOME/.quanta/quanta
cd $HOME/.quanta/quanta/ && go build -o quanta cmd/main.go

echo -e "${GREEN} Quanta was builded successfuly! Well, now you should add path to this folder :"
pwd
echo -e "into your system PATH variable. Enjoy the most lightweight package manager in the world! ${NC}"
